- docker-compose.yml
Added the following lines to both scraper and torrentio services
depends_on:
- mongodb
- postgres
> Added depends on to docker-compose.yml

- README.md
- docker-compose-metrics.yml
- docker-compose.yaml
- grafana/datasource.yml
- prometheus/prometheus.yml
- src/node/addon/src/lib/repository.js
- src/node/addon/src/serverless.js
This pull request introduces a new docker-compose-metrics.yml file, which includes services for Prometheus and Grafana. The primary goal is to add RabbitMQ monitoring and visualization capabilities directly through Grafana
Changes Made:
- Introduced the docker-compose-metrics.yml file, incorporating Prometheus and Grafana services.
- Updated the README to provide instructions on configuring Prometheus and Grafana to monitor RabbitMQ.
- Included datasource.yml and prometheus.yml configuration files to seamlessly integrate Grafana and Prometheus.
> Monitoring with Grafana and Prometheus

- docker-compose-metrics.yml
- docker-compose.yaml
Remove the default open ports to reduce the chances of: #54
For a casual user, they don't need to be concerned about things like this so a sane default is to not open the port.
For a more experienced user, they can manually open them.
> Critical security enhancements

- deployment/docker/.env.example
- src/node/consumer/src/lib/config.js
- src/node/consumer/src/lib/repository.js
Re: [sequelize docs](https://sequelize.org/docs/v6/core-concepts/model-basics/#synchronization-in-production) Alter is a bad idea in production.
Also print error message instead of sequelize error object as it's a bit verbose
> Remove alter param from database sync

- deployment/docker/docker-compose.yaml
RabbitMQ needs a persistent hostname per https://github.com/docker-library/rabbitmq/issues/392 otherwise it starts with a random one, losing data
Closes #75
> Add hostname to rabbit mq container

- README.md
The rarbg dump contains multiple movies and tv categories which are unique entries. The current insert command only grabs the categories "movies" and "tv" but not the multiple movies_*** and tv_*** categories. 
This command will also skip duplicates, so the SQL command won't error out and can be run on an existing database. Duplicate check is based on the hash of the specific torrent. 
In a recent PR this part of the command:  ```"createdAt", "updatedAt")``` was changed for `` \"createdAt\", \"updatedAt\") ``.
For me this new command will error out on this change, but maybe it works for others. In this PR I've reverted this change since that has been working before.
> Change SQL command to insert all movies and tv categories + skip duplicates

- src/node/addon/src/lib/config.js
Thanks @purple-emily for finding this.. 
This fixes a bug condition under which the consumer and the addon both try to use the same mongodb collection.
In "production", I was noticing addons would start to error / timeout when I had > 6 consumers running.
Post-change, I'm running 45 consumers with no timeouts :)
> Fix addon collection name

- .github/workflows/build_images.yaml
- src/node/addon-jackett/.dockerignore
- src/node/addon-jackett/Dockerfile
- src/node/addon/.dockerignore
- src/node/addon/Dockerfile
- src/node/consumer/.dockerignore
- src/node/consumer/Dockerfile
- src/producer/Dockerfile
This addition refactors the current GitHub Action image builder to add the following:
a. Updated dockerignore for eslint files, Dockerfile, and README file.
b. Update Dockerfile to add a new user and run container as new user, add basic health check for pm2.
a. Updated dockerignore for eslint files and Dockerfile
b. Update Dockerfile to add a new user and run container as new user, add basic health check for pm2.
a. Updated dockerignore for eslint files and Dockerfile
b. Update Dockerfile to add a new user and run container as new user, add basic health check for node, and set uid files as non-executable by non-root users.
a. Update Dockerfile to add a new user and run container as new user, add basic health check for node, and add fixes for multi-platform image builds.
> GitHub Action Refactor feat. multi-platform images

- src/node/consumer/Dockerfile
Resolve "pgrep: not found" issue
Added installation of the procps package in the builder stage to ensure the pgrep command is available in the final Docker image. This resolves the "pgrep: not found" issue in the HEALTHCHECK.
> Resolve "pgrep: not found" issue

- src/node/consumer/Dockerfile
This modification adds the installation of procps in the final stage, ensuring that the pgrep command is available for health check. My bad to oversee this the first time around. Sorry!
> pgrep command is part of the procps package, installed in the builder stage, but it's not present in the final stage.

- src/metadata/Configuration/logging.json
- src/metadata/Dockerfile
- src/metadata/Extensions/ConfigurationExtensions.cs
- src/metadata/Extensions/EnvironmentExtensions.cs
- src/metadata/Extensions/JsonSerializerExtensions.cs
- src/metadata/Extensions/ServiceCollectionExtensions.cs
- src/metadata/Extensions/WebApplicationBuilderExtensions.cs
- src/metadata/Features/Configuration/JobConfiguration.cs
- src/metadata/Features/Configuration/MongoConfiguration.cs
- src/metadata/Features/DeleteDownloadedImdbData/DeleteDownloadedImdbDataRequest.cs
- src/metadata/Features/DeleteDownloadedImdbData/DeleteDownloadedImdbDataRequestHandler.cs
- src/metadata/Features/DownloadImdbData/DownloadImdbDataJob.cs
- src/metadata/Features/DownloadImdbData/GetImdbDataRequest.cs
- src/metadata/Features/DownloadImdbData/GetImdbDataRequestHandler.cs
- src/metadata/Features/ImportImdbData/ImdbEntry.cs
- src/metadata/Features/ImportImdbData/ImdbMongoDbService.cs
- src/metadata/Features/ImportImdbData/ImportImdbDataRequest.cs
- src/metadata/Features/ImportImdbData/ImportImdbDataRequestHandler.cs
- src/metadata/Features/Jobs/BaseJob.cs
- src/metadata/Features/Jobs/IMetadataJob.cs
- src/metadata/Features/Jobs/JobScheduler.cs
- src/metadata/Features/Literals/CronExpressions.cs
- src/metadata/Features/Literals/HttpClients.cs
- src/metadata/GlobalUsings.cs
- src/metadata/Metadata.csproj
- src/metadata/Program.cs
We can use this collection as an alternative source to lookup imdb ids, which would be executed before name_to_imdb is called in the consumer.
As discussed in Discord, there is currently an issue where rate limiting may cause an IMDB id lookup to fail - this PR will address that by having a service that periodically updates and caches all possible IMDB ids from imdb's datasets.
> Create service to populate Imdb data collection within mongo

- src/node/consumer/package-lock.json
- src/node/consumer/package.json
- src/node/consumer/src/lib/mongo/interfaces/imdb_entry_attributes.ts
- src/node/consumer/src/lib/mongo/interfaces/mongo_metadata_query.ts
- src/node/consumer/src/lib/mongo/interfaces/mongo_repository.ts
- src/node/consumer/src/lib/mongo/models/imdb_entries_model.ts
- src/node/consumer/src/lib/mongo/mongo_repository.ts
- src/node/consumer/src/lib/services/metadata_service.ts
- src/node/consumer/src/setup/composition_root.ts
- src/node/consumer/src/setup/inversify_config.ts
- src/node/consumer/src/setup/ioc_types.ts
- src/node/consumer/test/services/mongo_repository.test.ts
- src/node/consumer/tsconfig.json
Adds the new imdb collection lookup into the consumer, so that it first tries to get from mongodb, then use the old methods if the id isn't found.
> Plug in the new mongo imdb lookups into the consumer

- src/producer/Features/Crawlers/Torrentio/TorrentioCrawler.cs
when torrentio/knightcrawler instances return invalid status codes on fetch requests for json payloads, pre-parsing of json, polly will catch in the policy wrapped resiliency handler
> Ensure we throw

- .github/workflows/base_image_workflow.yaml
- .github/workflows/build_addon.yaml
- .github/workflows/build_consumer.yaml
- .github/workflows/build_jackett-addon.yaml
- .github/workflows/build_metadata.yaml
- .github/workflows/build_producer.yaml
Also limits each to firing based on the path of changes in the push.
> Move workflow processing to base, and then one for each docker image

- src/node/consumer/src/lib/models/configuration/tracker_config.ts
- src/node/consumer/src/lib/services/cache_service.ts
- src/node/consumer/src/lib/services/tracker_service.ts
Also introduces the ability to reuse your PAT token. If its set, it'll be used on tracker calls.
> Fix Trackers TTL

- deployment/docker/docker-compose.yaml
- deployment/docker/src/components/knightcrawler.yaml
- deployment/docker/stack.env
- src/debrid-collector/requirements.txt
- src/producer/src/Configuration/scrapers.json
- src/producer/src/Features/Crawlers/Dmm/DMMFileDownloader.cs
- src/producer/src/Features/Crawlers/Dmm/DMMHttpClient.cs
- src/producer/src/Features/Crawlers/Dmm/DebridMediaManagerCrawler.cs
- src/producer/src/Features/Crawlers/Dmm/GithubConfiguration.cs
- src/producer/src/Features/Crawlers/Dmm/IDMMFileDownloader.cs
- src/producer/src/Features/Crawlers/Dmm/ServiceCollectionExtensions.cs
- src/producer/src/Features/JobSupport/ServiceCollectionExtensions.cs
- src/producer/src/GlobalUsings.cs
- src/producer/src/Program.cs
- src/producer/src/requirements.txt
- src/qbit-collector/requirements.txt
- src/shared/Extensions/DictionaryExtensions.cs
- src/shared/GlobalUsings.cs
- src/shared/Python/RTN/IRankTorrentName.cs
- src/shared/Python/RTN/RankTorrentName.cs
single call to github to download the repo archive.
remove need for PAT
update RTN to 0.2.13
change to batch_parse for title parsing from RTN
3 hour interval by default
> DMM Offline

- deployment/docker/config/qbit/qbittorrent.conf
- deployment/docker/docker-compose.yaml
- deployment/docker/src/components/knightcrawler.yaml
- deployment/docker/stack.env
- src/qbit-collector/Extensions/ServiceCollectionExtensions.cs
- src/qbit-collector/Features/Qbit/QBitRequestProcessor.cs
- src/qbit-collector/Features/Qbit/QbitConfiguration.cs
- src/qbit-collector/Features/Worker/WriteQbitMetadataConsumer.cs
Needs Testing - Written on ipad...
Concurrency Upped to 8 by default, and can be configured up to whatever the maximum number of ActiveTorrents is in qbit (which i've increased to 20)
DO NOT JUST ASSUME YOU CAN GO HIGHER THAN THIS
be reserved!
> Allow qbit concurrency to be configurable beyond the default prefetch

- deployment/docker/docker-compose.yaml
- deployment/docker/src/components/knightcrawler.yaml
- src/producer/src/Configuration/scrapers.json
- src/producer/src/Features/CrawlerSupport/BaseJsonCrawler.cs
- src/producer/src/Features/CrawlerSupport/BaseXmlCrawler.cs
- src/producer/src/Features/CrawlerSupport/Scraper.cs
- src/producer/src/Features/Crawlers/EzTv/EzTvCrawler.cs
- src/producer/src/Features/Crawlers/Nyaa/NyaaCrawler.cs
- src/producer/src/Features/Crawlers/Tgx/TgxCrawler.cs
- src/producer/src/Features/Crawlers/Tpb/TpbCrawler.cs
- src/producer/src/Features/Crawlers/Yts/YtsCrawler.cs
- After this change you can mount the scrapers.json file over the top of the one in the container to control urls, if a scraper is enabled or not, and the time period between scrapes
> Allow configuration of producer urls

- src/addon/src/lib/repository.js
After recent parser changes (which presumably discard some torrents *after* files end up in the files table), I found my addon erroring on certain IMDB queries.
It turns out the sequelize query which assembles the stream results performs a `LEFT OUTER JOIN` between the files table and the torrents table. Consequently, if theres' an infoHash in the files table which doesn't exist in the torrents table, the query will return `NULL` for all of the torrent fields, including `seeders`, `title`, etc.
I'm not sure why this happened, but it seems safer to use an `INNER JOIN`, such that only data which exists in both the files and torrents table is returned.
This PR simply effects this change, such that null results are no longer returned, and the addon doesn't error.
> INNER JOIN when selecting files and torrents to avoid null results

- src/addon/src/lib/streamInfo.js
Another minor UX fix here.. the original addon included code to avoid returning both `file.title` and `torrent.title` - if `file.title` included the contents of `torrent.title`, then only `torrent.title` will be returned.
Since we're now parsing titles better, most of the time `torrent.title` is a nice, friendly movie/series name.
This means that if `torrent.title` is `Fallout`, and `file.title` is 
`Fallout.2024.S01E01.MULTi.VF2.HDR.2160p.WEB.H265-FW.mkv`, the addon will only return `Fallout`.
The disadvantages here are:
1. The user can no longer parse the file details to make a decision about which stream to pick (based on audio codec for example)
2. Automation which uses the addon (the Prowlarr indexer, for example) don't return valid results (*these often split the results by …
> Always return title and filename

- src/addon/src/addon.js
Filters have been removed in the following commit: https://github.com/knightcrawler-stremio/knightcrawler/commit/ab17ef81be610005049d6ccc8c2a1417d18626b2#diff-748ff5015b225e4bd801eb1c6b5c60d239f46d8a96f85e24acc83b7ade8dadddL30
This commit re-adds them, so the user can filter by quality and size.
I haven't tested it yet, because i don't have a setup with enough torrents to test it.
> Re-add filter step in the processing of the streams

- src/addon/package-lock.json
- src/addon/package.json
Hey folks,
I'm a total nodejs noob, so LMK if this is not the right way to do this.. this PR simply updates the minimum required version of `all-debrid-api` to v1.2.0, which incorporades the `ip` query string in the URL, which will become an [alldebrid requirement](https://cdn.discordapp.com/attachments/701542427059814461/1233303462155128914/tempFileForShare_20240426-092648.jpg?ex=662f3ddb&is=662dec5b&hm=d0ae2cf27910915dce2c54b1ab63434d519788bb19f2908d1a17a78dcf939e2d&) in the next few weeks.
> Update all-debrid-api to v1.2.0 for new IP requirement
