knightcrawler-stremio/knightcrawler

- docker-compose.yml
- scraper/scrapers/1337x/1337x_api.js
1337x now uses Cloudflare which makes the scraper unable to load the site without [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr)
Added FlareSolverr to the docker-compose.yml and edited the 1337x scraper to use FlareSolverr to load the urls
> Add FlareSolverr fro 1337x

- README.md
A quick README update recording the process of importing the rarbg dump that's around. I haven't found the tpb dump yet :)
> Minimal docs on importing rarbg dump

- README.md
- docker-compose-metrics.yml
- docker-compose.yaml
- env/addon.env
- env/consumer.env
- env/producer.env
- src/node/addon-jackett/src/moch/alldebrid.js
- src/node/addon-jackett/src/moch/moch.js
- src/node/addon/ecosystem.config.cjs
- src/node/addon/package-lock.json
- src/node/addon/package.json
- src/node/addon/src/addon.js
- src/node/addon/src/lib/cache.js
- src/node/addon/src/lib/manifest.js
- src/node/addon/src/lib/streamInfo.js
- src/node/addon/src/moch/alldebrid.js
- src/node/addon/src/moch/moch.js
- src/node/consumer/src/lib/cache.js
- src/node/consumer/src/lib/config.js
- Changes references for `Selfhostio` to `KnightCrawler`
- Adds a background and logo to the main page
- Adds instructions to complete the database migration
> Renames project to Knight Crawler

- src/node/addon/src/lib/manifest.js
> remove extraneous v from manifest version

- src/node/addon/src/lib/config.js
Updated and replaced selfhostio entries with knightcrawler within src/node/addon/src/lib/config.js
Was previously still pointing to the old DB name of selfhostio
> Updated and replaced selfhostio entries with knightcrawler

- .github/workflows/build_images.yaml
- deployment/docker/docker-compose.yaml
- Adds a workflow that builds image on changes
- Replaces builds with omage in compose file
> Image build action

- README.md
Added alternative pgloader process using docker to import rarbg_db.sqlite db
> Added alternative pgloader process using docker

- README.md
> Add psql command for inserting non-exact movies and tv categories

- src/node/consumer/Dockerfile
Fixes #88 - the entrypoint was wrong in the Dockerfile
> Fix the entrypoint

- .github/workflows/build_images.yaml
As explained in a comment on the linked issue. Not 100% sure this will work as it's difficult to test beforehand. Once it does we should close the issue by hand.
> Try to fix GitHub action workflow (see #87)

- src/producer/Crawlers/Sites/DebridMediaManagerCrawler.cs
Fixes #95 by switching to git trees instead of the content api.
> Fix DMM so that all pages are enumerated

- src/producer/Configuration/scrapers.json
- src/producer/Crawlers/Sites/NyaaCrawler.cs
- src/producer/Extensions/ServiceCollectionExtensions.cs
- src/producer/Jobs/SyncNyaaJob.cs
> Adds Nyaa Crawler

- deployment/docker/docker-compose.yaml
- src/metadata/Dockerfile
- src/node/consumer/src/lib/mongo/interfaces/mongo_metadata_query.ts
- src/node/consumer/src/lib/mongo/mongo_repository.ts
- src/node/consumer/test/services/mongo_repository.test.ts
small hotfix to use fuzzy text lookups and actually utilise the new compound index. Forgot to change from Regex where case insensitive doesn't utilise text based indexing
> Hotfix: actually utilise the new compound index.

- src/node/addon/src/moch/premiumize.js
Potential fix for https://github.com/Gabisonfire/knightcrawler/issues/93
> Updated premiumize moch from upstream

- src/producer/Configuration/torrentio.json
- src/producer/Features/Crawlers/Torrentio/TorrentioCrawler.cs
- src/producer/Features/Crawlers/Torrentio/TorrentioScrapeInstance.cs
> change default retry window to be a larger delay

- README.md
I don't know why I didn't catch it before lol
> Change docker-compose to docker compose

- README.md
Centers the new logo introduced in #112  as follows:
> Center logo and introduction

- src/producer/Features/Crawlers/Dmm/DebridMediaManagerCrawler.cs
Forgot to remove the debug line for movies.
> remove log line of adult content

- src/node/consumer/src/lib/services/metadata_service.ts
- src/node/consumer/src/lib/services/torrent_entries_service.ts
- src/node/consumer/src/lib/services/torrent_file_service.ts
- src/node/consumer/src/lib/services/torrent_subtitle_service.ts
Fixes #140
Quite a serious issue
Will require re-processing of all entries in the files table where imdbSeason, imdbEpisode and KitsuEpisode are null or 0
> Fix series parsing

- src/node/consumer/package-lock.json
- src/node/consumer/package.json
- src/node/consumer/src/lib/services/torrent_entries_service.ts
- src/node/consumer/src/lib/services/torrent_file_service.ts
- src/producer/Features/Crawlers/Nyaa/NyaaCrawler.cs
should speed up massively especially if imdbIds are found from mongodb
> Simplification of parsing in consumer

- README.md
- deployment/docker/docker-compose.yaml
> Update compose versions 1.0.1, ready for tag push

- deployment/docker/.env.example
- deployment/docker/components/knightcrawler.yaml
- src/qbit-collector/Features/Qbit/QbitConfiguration.cs
- src/qbit-collector/Features/Trackers/TrackersService.cs
this allows people to use only the udp collection, only the tcp collection, or all.
> Allow trackers url to be configurable + version bump

- src/addon/src/lib/repository.js
Forgot to patch addon with schema changes
> Patch the addon

- src/producer/src/Configuration/scrapers.json
> update eztv url

- src/producer/src/Features/Crawlers/Dmm/ServiceCollectionExtensions.cs
Closes #217 
Adds a 10 minute timeout, instead of default 100s
> Add longer timeout for DMM
